export const BEACON_BADGES = [
  {
    id: "beacon-member",
    name: "Beacon Member",
    tag: "Starter",
    tone: "gold",
    icon: "BM",
    summary: "Created a Beacon account and joined the dashboard.",
    hint: "Log in with Discord once. This is the first mark every real Beacon profile gets.",
  },
  {
    id: "pioneer",
    name: "Pioneer",
    tag: "Legacy",
    tone: "gold",
    icon: "01",
    summary: "For the first wave of Beacon members, early accounts and early servers.",
    hint: "This combines the old earliest-days, Beacon 100 and first-server marks into one clean legacy badge.",
  },
  {
    id: "beacon-developer",
    name: "Beacon Developer",
    tag: "Official",
    tone: "orange",
    icon: "</>",
    summary: "Official developer badge for people who helped build Beacon itself.",
    hint: "Ship code, design, systems or infrastructure that becomes part of Beacon.",
  },
  {
    id: "verified",
    name: "Verified",
    tag: "Trusted",
    tone: "blue",
    icon: "OK",
    summary: "For known creators, community figures or trusted Beacon partners.",
    hint: "Be a public creator, Beacon CC, known partner or someone the team can verify manually.",
  },
  {
    id: "donator",
    name: "Donator",
    tag: "Supporter",
    tone: "green",
    icon: "$",
    summary: "Supported Beacon directly with a donation.",
    hint: "Donate to Beacon. Bigger support may unlock stronger donor tiers later.",
  },
  {
    id: "premium",
    name: "Premium",
    tag: "Paid",
    tone: "violet",
    icon: "PR",
    summary: "Bought Beacon Premium for a server.",
    hint: "Purchase Premium or Prestige on a server connected to your Beacon account.",
  },
  {
    id: "staff",
    name: "Staff",
    tag: "Team",
    tone: "blue",
    icon: "ST",
    summary: "Member of the Beacon staff team.",
    hint: "Reserved for people helping run support, moderation or community operations.",
  },
  {
    id: "helper",
    name: "Helper",
    tag: "Community",
    tone: "gold",
    icon: "HP",
    summary: "Helped other users enough for the team to notice.",
    hint: "Be useful in the community without farming it. Real help counts more than volume.",
  },
  {
    id: "bug-hunter",
    name: "Bug Hunter",
    tag: "Report",
    tone: "green",
    icon: "BH",
    summary: "Reported a real Beacon bug that got confirmed.",
    hint: "Send a clear report with steps, screenshots or logs so the issue can be fixed.",
  },
  {
    id: "server-booster",
    name: "Server Booster",
    tag: "Boost",
    tone: "orange",
    icon: "SB",
    summary: "Boosted the Beacon Discord server.",
    hint: "Boost the official Beacon server while your Discord account is connected.",
  },
  {
    id: "witness",
    name: "Witness",
    tag: "Event",
    tone: "blue",
    icon: "EV",
    summary: "Was present during a special launch, test or major Beacon moment.",
    hint: "Some badges only exist when something happens live. Be there when it does.",
  },
  {
    id: "the-beacon",
    name: "The Beacon",
    tag: "Rare",
    tone: "orange",
    icon: "BC",
    summary: "A rare manual badge for people who genuinely help Beacon stand out.",
    hint: "This one is noticed, not grinded.",
  },
  {
    id: "beacons-princess",
    name: "Beacon's Princess",
    tag: "???",
    tone: "gold",
    icon: "??",
    summary: "???",
    hint: "???",
  },
  {
    id: "found-the-light",
    name: "Found the Light",
    tag: "Easter Egg",
    tone: "green",
    icon: "FL",
    summary: "Found a hidden interaction somewhere on Beacon.",
    hint: "Watch small details on Beacon pages. Some things answer only after you notice the pattern.",
  },
  {
    id: "not-found",
    name: "404",
    tag: "Secret",
    tone: "orange",
    icon: "404",
    summary: "Found something that should not be there.",
    hint: "A wrong turn can still count, but only if you do more than stare at the error.",
  },
  {
    id: "lost-signal",
    name: "Lost Signal",
    tag: "Hidden",
    tone: "violet",
    icon: "LS",
    summary: "Discovered a hidden command, page or state most users never see.",
    hint: "A command exists where most people stop typing. Find the silence after the signal.",
  },
  {
    id: "night-owl",
    name: "Night Owl",
    tag: "Activity",
    tone: "blue",
    icon: "NO",
    summary: "Kept building late when everyone else was asleep.",
    hint: "Beacon remembers the quiet hours. Not every night counts, and not every action matters.",
  },
  {
    id: "command-relic",
    name: "Command Relic",
    tag: "Hidden",
    tone: "green",
    icon: "CR",
    summary: "Used Beacon commands in a very specific long-term pattern.",
    hint: "It is not about spam. It is about the right commands, in the right rhythm, for long enough.",
  },
  {
    id: "prismatic-key",
    name: "Prismatic Key",
    tag: "Secret",
    tone: "violet",
    icon: "PK",
    summary: "A secret badge connected to multiple parts of Beacon.",
    hint: "One feature is not enough. The key only forms when different systems line up.",
  },
  {
    id: "lucky-signal",
    name: "Lucky Signal",
    tag: "Drop",
    tone: "gold",
    icon: "LU",
    summary: "A rare random drop that appears during normal Beacon use.",
    hint: "You cannot force it, but you can be there when it happens.",
  },
];
